"""add return fields to bookings

Revision ID: 20a4049ecea4
Revises: 46df99b62ebd
Create Date: 2026-08-05 23:07:49.018771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20a4049ecea4'
down_revision: Union[str, Sequence[str], None] = '46df99b62ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


return_condition_enum = sa.Enum('fine', 'damaged', name='return_condition')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    return_condition_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('bookings', sa.Column('return_condition', return_condition_enum, nullable=True))
    op.add_column('bookings', sa.Column('damage_notes', sa.Text(), nullable=True))
    op.add_column('bookings', sa.Column('return_image', sa.String(length=500), nullable=True))
    op.add_column('bookings', sa.Column('collected_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'users', ['collected_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'collected_by_id')
    op.drop_column('bookings', 'return_image')
    op.drop_column('bookings', 'damage_notes')
    op.drop_column('bookings', 'return_condition')
    return_condition_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
