"""product variation color size and drop attributes

Revision ID: 20f63f05429d
Revises: c3e287315945
Create Date: 2026-08-04 18:27:50.879522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20f63f05429d'
down_revision: Union[str, Sequence[str], None] = 'c3e287315945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variations', sa.Column('color', sa.String(length=50), nullable=True))
    op.add_column('product_variations', sa.Column('size', sa.String(length=50), nullable=True))
    op.drop_column('product_variations', 'attributes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variations', sa.Column('attributes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('product_variations', 'size')
    op.drop_column('product_variations', 'color')
    # ### end Alembic commands ###
