"""add address to attendance

Revision ID: 46df99b62ebd
Revises: 4ae99eeba3da
Create Date: 2026-08-05 00:41:44.853862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46df99b62ebd'
down_revision: Union[str, Sequence[str], None] = '4ae99eeba3da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('check_in_address', sa.String(length=500), nullable=True))
    op.add_column('attendances', sa.Column('check_out_address', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendances', 'check_out_address')
    op.drop_column('attendances', 'check_in_address')
    # ### end Alembic commands ###
