"""add created_by_id to bookings

Revision ID: 93aeae09e17c
Revises: 84200913ec7a
Create Date: 2026-08-06 00:01:32.739301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93aeae09e17c'
down_revision: Union[str, Sequence[str], None] = '84200913ec7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'created_by_id')
    # ### end Alembic commands ###
