"""add product variations

Revision ID: c3e287315945
Revises: a497c8dd1410
Create Date: 2026-08-04 10:40:26.806018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3e287315945'
down_revision: Union[str, Sequence[str], None] = 'a497c8dd1410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_variations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('rent_price', sa.Float(), nullable=False),
    sa.Column('security_deposit', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('barcode_image', sa.String(length=500), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('gallery', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('sku')
    )
    op.drop_constraint(op.f('products_barcode_key'), 'products', type_='unique')
    op.drop_constraint(op.f('products_sku_key'), 'products', type_='unique')
    op.drop_column('products', 'gallery')
    op.drop_column('products', 'sku')
    op.drop_column('products', 'quantity')
    op.drop_column('products', 'is_available')
    op.drop_column('products', 'barcode_image')
    op.drop_column('products', 'barcode')
    op.drop_column('products', 'rent_price')
    op.drop_column('products', 'security_deposit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('security_deposit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('rent_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('barcode', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('barcode_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('gallery', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('products_sku_key'), 'products', ['sku'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('products_barcode_key'), 'products', ['barcode'], postgresql_nulls_not_distinct=False)
    op.drop_table('product_variations')
    # ### end Alembic commands ###
