"""add variation_id to bookings

Revision ID: faf7667c45da
Revises: 20f63f05429d
Create Date: 2026-08-04 21:18:43.116951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faf7667c45da'
down_revision: Union[str, Sequence[str], None] = '20f63f05429d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('variation_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'product_variations', ['variation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'variation_id')
    # ### end Alembic commands ###
